---
- include: redhat/main.yml
  when: ansible_os_family == "RedHat"

- include: vim.yml


- name: Install gitconfig.common
  template: src=gitconfig.common dest=~{{me}}/gitconfig.common owner={{me}} mode=0666

- name: Include gitconfig.common in ~/.gitconfig
  lineinfile: line="[include] path=gitconfig.common" dest=~{{me}}/.gitconfig create=yes owner={{me}}
